version: '3.6'

services:
  library-backend-api:
    container_name: backend
    #image: node:14
    build: ./
    command: npm run start:dev
    working_dir: /src/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library
      JWT_SECRETKEY: secret
      JWT_EXPIRED: 1d
    links:
      - postgres
    ports:
      - '3001:3000'
    volumes:
      - ./:/usr/src/

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library
